{{- if .Values.postgresql.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "mathison.fullname" . }}-postgres-headless
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mathison.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    {{- include "mathison.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: database
  ports:
    - name: tcp-postgresql
      port: 5432
      targetPort: tcp-postgresql
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "mathison.fullname" . }}-postgres
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mathison.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
spec:
  type: ClusterIP
  selector:
    {{- include "mathison.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: database
  ports:
    - name: tcp-postgresql
      port: 5432
      targetPort: tcp-postgresql
{{- end }}
