{{- if .Values.redis.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mathison.fullname" . }}-redis-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mathison.labels" . | nindent 4 }}
    app.kubernetes.io/component: cache
data:
  redis.conf: |
    maxmemory-policy allkeys-lru
    appendonly yes
    appendfsync everysec
{{- end }}
